alpha_eval: 0.95
alpha_train: 0.23
eval_eps: 0.341
lambda_actions_eval: 0.01
lambda_actions_train: 0.03
lambda_frames_eval: 0.02
lambda_frames_train: 0.0699999999999999
layer_sizes:
- 512
- 256
- 40
learn_clusters: true
lr: 0.0001
n_clusters: 14
n_frames: 9100
n_ot_eval:
- 25
- 1
n_ot_train:
- 25
- 1
radius_gw: 0.008
rho: 0.159
step_size: null
temp: 0.1
train_eps: 0.065
ub_actions: false
ub_frames: false
visualize: true
weight_decay: 1.0e-07
