alpha_eval: 0.21
alpha_train: 0.03
eval_eps: 0.048
lambda_actions_eval: 0.0999999999999999
lambda_actions_train: 0.09
lambda_frames_eval: 0.01
lambda_frames_train: 0.01
layer_sizes:
- 650
- 300
- 40
learn_clusters: true
lr: 1.0e-05
n_clusters: 5
n_frames: 205
n_ot_eval:
- 25
- 1
n_ot_train:
- 25
- 1
radius_gw: 0.092
rho: 0.012
step_size: null
temp: 0.1
train_eps: 0.001
ub_actions: true
ub_frames: true
visualize: true
weight_decay: 0.001
