alpha_eval: 0.08
alpha_train: 0.14
eval_eps: 0.175
lambda_actions_eval: 0.0699999999999999
lambda_actions_train: 0.03
lambda_frames_eval: 0.01
lambda_frames_train: 0.08
layer_sizes:
- 650
- 300
- 40
learn_clusters: true
lr: 1.0e-05
n_clusters: 3
n_frames: 60
n_ot_eval:
- 25
- 1
n_ot_train:
- 25
- 1
radius_gw: 0.038
rho: 0.044
step_size: null
temp: 0.1
train_eps: 0.309
ub_actions: false
ub_frames: false
visualize: true
weight_decay: 0.001
