alpha_eval: 0.15
alpha_train: 0.62
eval_eps: 0.009
lambda_actions_eval: 0.0999999999999999
lambda_actions_train: 0.08
lambda_frames_eval: 0.03
lambda_frames_train: 0.05
layer_sizes:
- 650
- 300
- 40
learn_clusters: true
lr: 0.1
n_clusters: 3
n_frames: 30
n_ot_eval:
- 25
- 1
n_ot_train:
- 25
- 1
radius_gw: 0.009
rho: 0.135
step_size: null
temp: 0.1
train_eps: 0.016
ub_actions: false
ub_frames: false
visualize: true
weight_decay: 1.0e-08
